### ISSUE TITLE
Problem while running the script

### ISSUE THREAD

**Issue by vibhorag** [ajasja/calculate_dihedrals#1]
Hello
I wanted to calculate the torsion angles for my protein.
As you directed in your instruction I downloaded bonth tcl scripts and passed following command
source calculate_dihedrals.tcl
print_sidechain_dihedrals A "resid 1 to 10" top dihedral.angles

it gave me following error
can't read "result": no such variable

I see result variable in both the tcl scripts.Shoud I need to modify the script.There might be bug in the script

Thanks
Vibhor

**Comment by ajasja** [comment]
Sorry, for the late reply (I didn't get the github notification per e-mail).
Indeed there was a bug. I hope it is fixed now (in commit 93c511afcabf33bd0f97b8d6d87bf2817e4ed050). If not please reopen the issue.
