### ISSUE TITLE
output file

### ISSUE THREAD

**Issue by FidanSumbul** [ajasja/calculate_dihedrals#3]
Hi,
This is exactly what i was looking for. Thank you very much for sharing you scripts.
But I have a question about the output file. In your example output file, all the first column is zero and Ala also has 3 columns. So I got confused which column is which dihedral angle?
If it is, phi, psi, Chi1 ..., then why the first one is zero, and Ala has Chi1?

Thank you in advance for your reply.
Best,
Fidan.

**Comment by ajasja** [comment]
Hi,

I'm happy that the scripts help:) 
The 0 column is the frame number (in case you would like to analyze an entire trajectory.
The relevant code is here
https://github.com/ajasja/calculate_dihedrals/blob/master/calculate_dihedrals.tcl#L192

I really should have mentioned that in the documentation.

Best,
Ajasja

**Comment by FidanSumbul** [comment]
Thank you for the fast reply. Then it goes like, 
resid resname framenumber phi psi chi1 chi2 ...
is that right?

**Comment by ajasja** [comment]
Yes, that is correct.
